### ISSUE TITLE
Refactor subclasses of java.awt.Component

### ISSUE THREAD

**Issue by RichardWarburton** [AdoptOpenJDK/PatchReview#1]
several subclasses of java.awt.Component implement the getListeners method identically.  Investigate whether all should implement that method, and whether its possible to refactor the code without changing the public API.

**Comment by mikeb01** [comment]
I think this would be a nice refactoring, but should kept as separate patch to the warnings fixes.

**Comment by karianna** [comment]
no longer an active project
