### ISSUE TITLE
Mani's Patches Reviewed

### ISSUE THREAD

**Issue by mikeb01** [AdoptOpenJDK/PatchReview#2]
I reviewed all of Mani's patches some time ago and feedback a few comments.  All of which were met.  Up to you guys if you feel you need another pass through his patches.

**Comment by karianna** [comment]
Hi Mike, was this _all_ of them? there's like 120+!

**Comment by mikeb01** [comment]
Yes, most of the changes were fairly trivial.  Some patches only contained a couple of line changes.

**Comment by karianna** [comment]
Cool, I'm going to get the group to go over them again for practice + OpenJDK code base has moved on a bit.  It's awesome you've reviewed them all though, means we've got our safety pants on :-)
